<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2f6nkjk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2f6nkjk/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2f6nkjk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2f6nkjk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2f6nkjk\appProdProjectContainer([
    'container.build_hash' => '2f6nkjk',
    'container.build_id' => '2e46d750',
    'container.build_time' => 1674289905,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2f6nkjk');
