<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5aa6er\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5aa6er/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerB5aa6er.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerB5aa6er\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerB5aa6er\appProdProjectContainer([
    'container.build_hash' => 'B5aa6er',
    'container.build_id' => '92bf73a0',
    'container.build_time' => 1669066565,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5aa6er');
